function getData() {
  // copy and paste JSON here
  // data = [{"id":"j1_1","text":"Root","icon":true,"li_attr":{"id":"j1_1"},"a_attr":{"href":"#","id":"j1_1_anchor"},"state":{"loaded":true,"opened":true,"selected":true,"disabled":false},"data":{},"parent":"#"},{"id":"j1_2","text":"Coding","icon":true,"li_attr":{"id":"j1_2"},"a_attr":{"href":"#","id":"j1_2_anchor"},"state":{"loaded":true,"opened":true,"selected":false,"disabled":false},"data":{},"parent":"j1_1"},{"id":"j1_3","text":"AI","icon":true,"li_attr":{"id":"j1_3"},"a_attr":{"href":"#","id":"j1_3_anchor"},"state":{"loaded":true,"opened":false,"selected":false,"disabled":false},"data":{},"parent":"j1_2"},{"id":"j1_6","text":"Project Managment","icon":true,"li_attr":{"id":"j1_6"},"a_attr":{"href":"#","id":"j1_6_anchor"},"state":{"loaded":true,"opened":false,"selected":false,"disabled":false},"data":{},"parent":"j1_2"},{"id":"j1_4","text":"Design","icon":true,"li_attr":{"id":"j1_4"},"a_attr":{"href":"#","id":"j1_4_anchor"},"state":{"loaded":true,"opened":true,"selected":false,"disabled":false},"data":{},"parent":"j1_1"},{"id":"j1_5","text":"CodeSchool - Fundamentals of Design","icon":true,"li_attr":{"id":"j1_5"},"a_attr":{"href":"#","id":"j1_5_anchor"},"state":{"loaded":true,"opened":true,"selected":false,"disabled":false},"data":{},"parent":"j1_4"},{"id":"j1_7","text":"Typography","icon":true,"li_attr":{"id":"j1_7"},"a_attr":{"href":"#","id":"j1_7_anchor"},"state":{"loaded":true,"opened":false,"selected":false,"disabled":false},"data":{},"parent":"j1_5"},{"id":"j1_9","text":"Serif (Attributes, Feel, Application) ","icon":true,"li_attr":{"id":"j1_9"},"a_attr":{"href":"#","id":"j1_9_anchor"},"state":{"loaded":true,"opened":false,"selected":false,"disabled":false},"data":{},"parent":"j1_7"},{"id":"j1_11","text":"Humanist","icon":true,"li_attr":{"id":"j1_11"},"a_attr":{"href":"#","id":"j1_11_anchor"},"state":{"loaded":true,"opened":false,"selected":false,"disabled":false},"data":{},"parent":"j1_9"},{"id":"j1_12","text":"Transitional","icon":true,"li_attr":{"id":"j1_12"},"a_attr":{"href":"#","id":"j1_12_anchor"},"state":{"loaded":true,"opened":false,"selected":false,"disabled":false},"data":{},"parent":"j1_9"},{"id":"j1_13","text":"Modern","icon":true,"li_attr":{"id":"j1_13"},"a_attr":{"href":"#","id":"j1_13_anchor"},"state":{"loaded":true,"opened":false,"selected":false,"disabled":false},"data":{},"parent":"j1_9"},{"id":"j1_14","text":"Egyptian/Slab ","icon":true,"li_attr":{"id":"j1_14"},"a_attr":{"href":"#","id":"j1_14_anchor"},"state":{"loaded":true,"opened":false,"selected":false,"disabled":false},"data":{},"parent":"j1_9"},{"id":"j1_10","text":"San-Serif (Attributes, Feel, Application) ","icon":true,"li_attr":{"id":"j1_10"},"a_attr":{"href":"#","id":"j1_10_anchor"},"state":{"loaded":true,"opened":false,"selected":false,"disabled":false},"data":{},"parent":"j1_7"},{"id":"j1_15","text":"Humanist","icon":true,"li_attr":{"id":"j1_15"},"a_attr":{"href":"#","id":"j1_15_anchor"},"state":{"loaded":true,"opened":false,"selected":false,"disabled":false},"data":{},"parent":"j1_10"},{"id":"j1_16","text":"Transitional","icon":true,"li_attr":{"id":"j1_16"},"a_attr":{"href":"#","id":"j1_16_anchor"},"state":{"loaded":true,"opened":false,"selected":false,"disabled":false},"data":{},"parent":"j1_10"},{"id":"j1_17","text":"Geometric","icon":true,"li_attr":{"id":"j1_17"},"a_attr":{"href":"#","id":"j1_17_anchor"},"state":{"loaded":true,"opened":false,"selected":false,"disabled":false},"data":{},"parent":"j1_10"},{"id":"j1_18","text":"Script","icon":true,"li_attr":{"id":"j1_18"},"a_attr":{"href":"#","id":"j1_18_anchor"},"state":{"loaded":true,"opened":false,"selected":false,"disabled":false},"data":{},"parent":"j1_7"},{"id":"j1_19","text":"Mixing Fonts","icon":true,"li_attr":{"id":"j1_19"},"a_attr":{"href":"#","id":"j1_19_anchor"},"state":{"loaded":true,"opened":false,"selected":false,"disabled":false},"data":{},"parent":"j1_7"},{"id":"j1_21","text":"Do's (3)","icon":true,"li_attr":{"id":"j1_21"},"a_attr":{"href":"#","id":"j1_21_anchor"},"state":{"loaded":true,"opened":false,"selected":false,"disabled":false},"data":{},"parent":"j1_19"},{"id":"j1_22","text":"Dont's (2)","icon":true,"li_attr":{"id":"j1_22"},"a_attr":{"href":"#","id":"j1_22_anchor"},"state":{"loaded":true,"opened":false,"selected":false,"disabled":false},"data":{},"parent":"j1_19"},{"id":"j1_20","text":"Font Size","icon":true,"li_attr":{"id":"j1_20"},"a_attr":{"href":"#","id":"j1_20_anchor"},"state":{"loaded":true,"opened":false,"selected":false,"disabled":false},"data":{},"parent":"j1_7"},{"id":"j1_23","text":"Leading","icon":true,"li_attr":{"id":"j1_23"},"a_attr":{"href":"#","id":"j1_23_anchor"},"state":{"loaded":true,"opened":false,"selected":false,"disabled":false},"data":{},"parent":"j1_7"},{"id":"j1_24","text":"Line Widths","icon":true,"li_attr":{"id":"j1_24"},"a_attr":{"href":"#","id":"j1_24_anchor"},"state":{"loaded":true,"opened":false,"selected":false,"disabled":false},"data":{},"parent":"j1_7"},{"id":"j1_8","text":"Color Theory","icon":true,"li_attr":{"id":"j1_8"},"a_attr":{"href":"#","id":"j1_8_anchor"},"state":{"loaded":true,"opened":false,"selected":false,"disabled":false},"data":{},"parent":"j1_5"},{"id":"j1_28","text":"Color Selection","icon":true,"li_attr":{"id":"j1_28"},"a_attr":{"href":"#","id":"j1_28_anchor"},"state":{"loaded":true,"opened":false,"selected":false,"disabled":false},"data":{},"parent":"j1_8"},{"id":"j1_25","text":"CMY","icon":true,"li_attr":{"id":"j1_25"},"a_attr":{"href":"#","id":"j1_25_anchor"},"state":{"loaded":true,"opened":false,"selected":false,"disabled":false},"data":{},"parent":"j1_28"},{"id":"j1_26","text":"RGB","icon":true,"li_attr":{"id":"j1_26"},"a_attr":{"href":"#","id":"j1_26_anchor"},"state":{"loaded":true,"opened":false,"selected":false,"disabled":false},"data":{},"parent":"j1_28"},{"id":"j1_27","text":"HSL","icon":true,"li_attr":{"id":"j1_27"},"a_attr":{"href":"#","id":"j1_27_anchor"},"state":{"loaded":true,"opened":false,"selected":false,"disabled":false},"data":{},"parent":"j1_28"},{"id":"j1_29","text":"Schemes","icon":true,"li_attr":{"id":"j1_29"},"a_attr":{"href":"#","id":"j1_29_anchor"},"state":{"loaded":true,"opened":false,"selected":false,"disabled":false},"data":{},"parent":"j1_8"},{"id":"j1_30","text":"Monochromatic","icon":true,"li_attr":{"id":"j1_30"},"a_attr":{"href":"#","id":"j1_30_anchor"},"state":{"loaded":true,"opened":false,"selected":false,"disabled":false},"data":{},"parent":"j1_29"},{"id":"j1_31","text":"Analagous","icon":true,"li_attr":{"id":"j1_31"},"a_attr":{"href":"#","id":"j1_31_anchor"},"state":{"loaded":true,"opened":false,"selected":false,"disabled":false},"data":{},"parent":"j1_29"},{"id":"j1_32","text":"Complimentary","icon":true,"li_attr":{"id":"j1_32"},"a_attr":{"href":"#","id":"j1_32_anchor"},"state":{"loaded":true,"opened":false,"selected":false,"disabled":false},"data":{},"parent":"j1_29"}];
  data = [
    {
        "id":"j1_1",
        "text":"Root",
        "icon":"../img/folder.png",
        "li_attr":{
            "id":"j1_1"
        },
        "a_attr":{
            "href":"#",
            "id":"j1_1_anchor"
        },
        "state":{
            "loaded":true,
            "opened":true,
            "selected":false,
            "disabled":false
        },
        "data":{
            "create_date":16839,
            "marked":false,
            "success":0,
            "failure":0,
            "audio_path":null,
            "note":null,
            "other":null
        },
        "parent":"#"
    },
    {
        "id":"j1_2",
        "text":"Coding",
        "icon":"../img/folder.png",
        "li_attr":{
            "id":"j1_2"
        },
        "a_attr":{
            "href":"#",
            "id":"j1_2_anchor"
        },
        "state":{
            "loaded":true,
            "opened":false,
            "selected":false,
            "disabled":false
        },
        "data":{
            "create_date":16839,
            "marked":false,
            "success":0,
            "failure":0,
            "audio_path":null,
            "note":null,
            "other":null
        },
        "parent":"j1_1"
    },
    {
        "id":"j1_5",
        "text":"Project Management",
        "icon":"../img/red-x.png",
        "li_attr":{
            "id":"j1_5"
        },
        "a_attr":{
            "href":"#",
            "id":"j1_5_anchor"
        },
        "state":{
            "loaded":true,
            "opened":false,
            "selected":false,
            "disabled":false
        },
        "data":{
            "create_date":16839,
            "marked":true,
            "success":0,
            "failure":0,
            "audio_path":null,
            "note":null,
            "other":null
        },
        "parent":"j1_2"
    },
    {
        "id":"j1_6",
        "text":"Artificial Intelligence ",
        "icon":"../img/red-x.png",
        "li_attr":{
            "id":"j1_6"
        },
        "a_attr":{
            "href":"#",
            "id":"j1_6_anchor"
        },
        "state":{
            "loaded":true,
            "opened":false,
            "selected":false,
            "disabled":false
        },
        "data":{
            "create_date":16839,
            "marked":true,
            "success":0,
            "failure":0,
            "audio_path":null,
            "note":null,
            "other":null
        },
        "parent":"j1_2"
    },
    {
        "id":"j1_3",
        "text":"Design",
        "icon":"../img/folder.png",
        "li_attr":{
            "id":"j1_3"
        },
        "a_attr":{
            "href":"#",
            "id":"j1_3_anchor"
        },
        "state":{
            "loaded":true,
            "opened":false,
            "selected":false,
            "disabled":false
        },
        "data":{
            "create_date":16839,
            "marked":false,
            "success":0,
            "failure":0,
            "audio_path":null,
            "note":null,
            "other":null
        },
        "parent":"j1_1"
    },
    {
        "id":"j1_7",
        "text":"CodeSchool - Fundamentals of Design ",
        "icon":"../img/folder.png",
        "li_attr":{
            "id":"j1_7"
        },
        "a_attr":{
            "href":"#",
            "id":"j1_7_anchor"
        },
        "state":{
            "loaded":true,
            "opened":true,
            "selected":false,
            "disabled":false
        },
        "data":{
            "create_date":16839,
            "marked":false,
            "success":0,
            "failure":0,
            "audio_path":null,
            "note":null,
            "other":null
        },
        "parent":"j1_3"
    },
    {
        "id":"j1_9",
        "text":"Typography",
        "icon":"../img/folder.png",
        "li_attr":{
            "id":"j1_9"
        },
        "a_attr":{
            "href":"#",
            "id":"j1_9_anchor"
        },
        "state":{
            "loaded":true,
            "opened":false,
            "selected":false,
            "disabled":false
        },
        "data":{
            "create_date":16839,
            "marked":false,
            "success":0,
            "failure":0,
            "audio_path":null,
            "note":null,
            "other":null
        },
        "parent":"j1_7"
    },
    {
        "id":"j1_11",
        "text":"Serif (Attributes, Feel, Application)",
        "icon":"../img/folder.png",
        "li_attr":{
            "id":"j1_11"
        },
        "a_attr":{
            "href":"#",
            "id":"j1_11_anchor"
        },
        "state":{
            "loaded":true,
            "opened":true,
            "selected":false,
            "disabled":false
        },
        "data":{
            "create_date":16839,
            "marked":false,
            "success":0,
            "failure":0,
            "audio_path":null,
            "note":null,
            "other":null
        },
        "parent":"j1_9"
    },
    {
        "id":"j1_18",
        "text":"Humanist",
        "icon":"../img/folder.png",
        "li_attr":{
            "id":"j1_18"
        },
        "a_attr":{
            "href":"#",
            "id":"j1_18_anchor"
        },
        "state":{
            "loaded":true,
            "opened":false,
            "selected":false,
            "disabled":false
        },
        "data":{
            "create_date":16839,
            "marked":false,
            "success":0,
            "failure":0,
            "audio_path":null,
            "note":null,
            "other":null
        },
        "parent":"j1_11"
    },
    {
        "id":"j1_19",
        "text":"Transitional",
        "icon":"../img/folder.png",
        "li_attr":{
            "id":"j1_19"
        },
        "a_attr":{
            "href":"#",
            "id":"j1_19_anchor"
        },
        "state":{
            "loaded":true,
            "opened":false,
            "selected":false,
            "disabled":false
        },
        "data":{
            "create_date":16839,
            "marked":false,
            "success":0,
            "failure":0,
            "audio_path":null,
            "note":null,
            "other":null
        },
        "parent":"j1_11"
    },
    {
        "id":"j1_20",
        "text":"Modern",
        "icon":"../img/folder.png",
        "li_attr":{
            "id":"j1_20"
        },
        "a_attr":{
            "href":"#",
            "id":"j1_20_anchor"
        },
        "state":{
            "loaded":true,
            "opened":false,
            "selected":false,
            "disabled":false
        },
        "data":{
            "create_date":16839,
            "marked":false,
            "success":0,
            "failure":0,
            "audio_path":null,
            "note":null,
            "other":null
        },
        "parent":"j1_11"
    },
    {
        "id":"j1_21",
        "text":"Egyptian/Slab",
        "icon":"../img/folder.png",
        "li_attr":{
            "id":"j1_21"
        },
        "a_attr":{
            "href":"#",
            "id":"j1_21_anchor"
        },
        "state":{
            "loaded":true,
            "opened":false,
            "selected":false,
            "disabled":false
        },
        "data":{
            "create_date":16839,
            "marked":false,
            "success":0,
            "failure":0,
            "audio_path":null,
            "note":null,
            "other":null
        },
        "parent":"j1_11"
    },
    {
        "id":"j1_12",
        "text":"San-Serif (Attributes, Feel, Application)",
        "icon":"../img/folder.png",
        "li_attr":{
            "id":"j1_12"
        },
        "a_attr":{
            "href":"#",
            "id":"j1_12_anchor"
        },
        "state":{
            "loaded":true,
            "opened":true,
            "selected":false,
            "disabled":false
        },
        "data":{
            "create_date":16839,
            "marked":false,
            "success":0,
            "failure":0,
            "audio_path":null,
            "note":null,
            "other":null
        },
        "parent":"j1_9"
    },
    {
        "id":"j1_22",
        "text":"Humanist",
        "icon":"../img/folder.png",
        "li_attr":{
            "id":"j1_22"
        },
        "a_attr":{
            "href":"#",
            "id":"j1_22_anchor"
        },
        "state":{
            "loaded":true,
            "opened":false,
            "selected":false,
            "disabled":false
        },
        "data":{
            "create_date":16839,
            "marked":false,
            "success":0,
            "failure":0,
            "audio_path":null,
            "note":null,
            "other":null
        },
        "parent":"j1_12"
    },
    {
        "id":"j1_23",
        "text":"Transitional",
        "icon":"../img/folder.png",
        "li_attr":{
            "id":"j1_23"
        },
        "a_attr":{
            "href":"#",
            "id":"j1_23_anchor"
        },
        "state":{
            "loaded":true,
            "opened":false,
            "selected":false,
            "disabled":false
        },
        "data":{
            "create_date":16839,
            "marked":false,
            "success":0,
            "failure":0,
            "audio_path":null,
            "note":null,
            "other":null
        },
        "parent":"j1_12"
    },
    {
        "id":"j1_24",
        "text":"Geometric",
        "icon":"../img/folder.png",
        "li_attr":{
            "id":"j1_24"
        },
        "a_attr":{
            "href":"#",
            "id":"j1_24_anchor"
        },
        "state":{
            "loaded":true,
            "opened":false,
            "selected":false,
            "disabled":false
        },
        "data":{
            "create_date":16839,
            "marked":false,
            "success":0,
            "failure":0,
            "audio_path":null,
            "note":null,
            "other":null
        },
        "parent":"j1_12"
    },
    {
        "id":"j1_13",
        "text":"Script",
        "icon":"../img/folder.png",
        "li_attr":{
            "id":"j1_13"
        },
        "a_attr":{
            "href":"#",
            "id":"j1_13_anchor"
        },
        "state":{
            "loaded":true,
            "opened":false,
            "selected":false,
            "disabled":false
        },
        "data":{
            "create_date":16839,
            "marked":false,
            "success":0,
            "failure":0,
            "audio_path":null,
            "note":null,
            "other":null
        },
        "parent":"j1_9"
    },
    {
        "id":"j1_14",
        "text":"Mixing Fonts",
        "icon":"../img/folder.png",
        "li_attr":{
            "id":"j1_14"
        },
        "a_attr":{
            "href":"#",
            "id":"j1_14_anchor"
        },
        "state":{
            "loaded":true,
            "opened":true,
            "selected":false,
            "disabled":false
        },
        "data":{
            "create_date":16839,
            "marked":false,
            "success":0,
            "failure":0,
            "audio_path":null,
            "note":null,
            "other":null
        },
        "parent":"j1_9"
    },
    {
        "id":"j1_25",
        "text":"Do's (3)",
        "icon":"../img/folder.png",
        "li_attr":{
            "id":"j1_25"
        },
        "a_attr":{
            "href":"#",
            "id":"j1_25_anchor"
        },
        "state":{
            "loaded":true,
            "opened":false,
            "selected":false,
            "disabled":false
        },
        "data":{
            "create_date":16839,
            "marked":false,
            "success":0,
            "failure":0,
            "audio_path":null,
            "note":null,
            "other":null
        },
        "parent":"j1_14"
    },
    {
        "id":"j1_26",
        "text":"Dont's (2)",
        "icon":"../img/folder.png",
        "li_attr":{
            "id":"j1_26"
        },
        "a_attr":{
            "href":"#",
            "id":"j1_26_anchor"
        },
        "state":{
            "loaded":true,
            "opened":false,
            "selected":false,
            "disabled":false
        },
        "data":{
            "create_date":16839,
            "marked":false,
            "success":0,
            "failure":0,
            "audio_path":null,
            "note":null,
            "other":null
        },
        "parent":"j1_14"
    },
    {
        "id":"j1_15",
        "text":"Font Size",
        "icon":"../img/folder.png",
        "li_attr":{
            "id":"j1_15"
        },
        "a_attr":{
            "href":"#",
            "id":"j1_15_anchor"
        },
        "state":{
            "loaded":true,
            "opened":false,
            "selected":false,
            "disabled":false
        },
        "data":{
            "create_date":16839,
            "marked":false,
            "success":0,
            "failure":0,
            "audio_path":null,
            "note":null,
            "other":null
        },
        "parent":"j1_9"
    },
    {
        "id":"j1_16",
        "text":"Leading",
        "icon":"../img/folder.png",
        "li_attr":{
            "id":"j1_16"
        },
        "a_attr":{
            "href":"#",
            "id":"j1_16_anchor"
        },
        "state":{
            "loaded":true,
            "opened":false,
            "selected":false,
            "disabled":false
        },
        "data":{
            "create_date":16839,
            "marked":false,
            "success":0,
            "failure":0,
            "audio_path":null,
            "note":null,
            "other":null
        },
        "parent":"j1_9"
    },
    {
        "id":"j1_17",
        "text":"Line Widths",
        "icon":"../img/folder.png",
        "li_attr":{
            "id":"j1_17"
        },
        "a_attr":{
            "href":"#",
            "id":"j1_17_anchor"
        },
        "state":{
            "loaded":true,
            "opened":false,
            "selected":false,
            "disabled":false
        },
        "data":{
            "create_date":16839,
            "marked":false,
            "success":0,
            "failure":0,
            "audio_path":null,
            "note":null,
            "other":null
        },
        "parent":"j1_9"
    },
    {
        "id":"j1_10",
        "text":"Color Theory",
        "icon":"../img/folder.png",
        "li_attr":{
            "id":"j1_10"
        },
        "a_attr":{
            "href":"#",
            "id":"j1_10_anchor"
        },
        "state":{
            "loaded":true,
            "opened":true,
            "selected":false,
            "disabled":false
        },
        "data":{
            "create_date":16839,
            "marked":false,
            "success":0,
            "failure":0,
            "audio_path":null,
            "note":null,
            "other":null
        },
        "parent":"j1_7"
    },
    {
        "id":"j1_27",
        "text":"Color Selection",
        "icon":"../img/folder.png",
        "li_attr":{
            "id":"j1_27"
        },
        "a_attr":{
            "href":"#",
            "id":"j1_27_anchor"
        },
        "state":{
            "loaded":true,
            "opened":true,
            "selected":false,
            "disabled":false
        },
        "data":{
            "create_date":16839,
            "marked":false,
            "success":0,
            "failure":0,
            "audio_path":null,
            "note":null,
            "other":null
        },
        "parent":"j1_10"
    },
    {
        "id":"j1_29",
        "text":"CMY",
        "icon":"../img/folder.png",
        "li_attr":{
            "id":"j1_29"
        },
        "a_attr":{
            "href":"#",
            "id":"j1_29_anchor"
        },
        "state":{
            "loaded":true,
            "opened":false,
            "selected":false,
            "disabled":false
        },
        "data":{
            "create_date":16839,
            "marked":false,
            "success":0,
            "failure":0,
            "audio_path":null,
            "note":null,
            "other":null
        },
        "parent":"j1_27"
    },
    {
        "id":"j1_30",
        "text":"RGB",
        "icon":"../img/folder.png",
        "li_attr":{
            "id":"j1_30"
        },
        "a_attr":{
            "href":"#",
            "id":"j1_30_anchor"
        },
        "state":{
            "loaded":true,
            "opened":false,
            "selected":false,
            "disabled":false
        },
        "data":{
            "create_date":16839,
            "marked":false,
            "success":0,
            "failure":0,
            "audio_path":null,
            "note":null,
            "other":null
        },
        "parent":"j1_27"
    },
    {
        "id":"j1_31",
        "text":"HSL",
        "icon":"../img/folder.png",
        "li_attr":{
            "id":"j1_31"
        },
        "a_attr":{
            "href":"#",
            "id":"j1_31_anchor"
        },
        "state":{
            "loaded":true,
            "opened":false,
            "selected":false,
            "disabled":false
        },
        "data":{
            "create_date":16839,
            "marked":false,
            "success":0,
            "failure":0,
            "audio_path":null,
            "note":null,
            "other":null
        },
        "parent":"j1_27"
    },
    {
        "id":"j1_28",
        "text":"Schemes",
        "icon":"../img/folder.png",
        "li_attr":{
            "id":"j1_28"
        },
        "a_attr":{
            "href":"#",
            "id":"j1_28_anchor"
        },
        "state":{
            "loaded":true,
            "opened":true,
            "selected":false,
            "disabled":false
        },
        "data":{
            "create_date":16839,
            "marked":false,
            "success":0,
            "failure":0,
            "audio_path":null,
            "note":null,
            "other":null
        },
        "parent":"j1_10"
    },
    {
        "id":"j1_32",
        "text":"Monochromatic",
        "icon":"../img/folder.png",
        "li_attr":{
            "id":"j1_32"
        },
        "a_attr":{
            "href":"#",
            "id":"j1_32_anchor"
        },
        "state":{
            "loaded":true,
            "opened":false,
            "selected":false,
            "disabled":false
        },
        "data":{
            "create_date":16839,
            "marked":false,
            "success":0,
            "failure":0,
            "audio_path":null,
            "note":null,
            "other":null
        },
        "parent":"j1_28"
    },
    {
        "id":"j1_33",
        "text":"Complimentary ",
        "icon":"../img/folder.png",
        "li_attr":{
            "id":"j1_33"
        },
        "a_attr":{
            "href":"#",
            "id":"j1_33_anchor"
        },
        "state":{
            "loaded":true,
            "opened":false,
            "selected":false,
            "disabled":false
        },
        "data":{
            "create_date":16839,
            "marked":false,
            "success":0,
            "failure":0,
            "audio_path":null,
            "note":null,
            "other":null
        },
        "parent":"j1_28"
    },
    {
        "id":"j1_34",
        "text":"Analogous",
        "icon":"../img/folder.png",
        "li_attr":{
            "id":"j1_34"
        },
        "a_attr":{
            "href":"#",
            "id":"j1_34_anchor"
        },
        "state":{
            "loaded":true,
            "opened":false,
            "selected":false,
            "disabled":false
        },
        "data":{
            "create_date":16839,
            "marked":false,
            "success":0,
            "failure":0,
            "audio_path":null,
            "note":null,
            "other":null
        },
        "parent":"j1_28"
    },
    {
        "id":"j1_4",
        "text":"Science",
        "icon":"../img/folder.png",
        "li_attr":{
            "id":"j1_4"
        },
        "a_attr":{
            "href":"#",
            "id":"j1_4_anchor"
        },
        "state":{
            "loaded":true,
            "opened":true,
            "selected":false,
            "disabled":false
        },
        "data":{
            "create_date":16839,
            "marked":false,
            "success":0,
            "failure":0,
            "audio_path":null,
            "note":null,
            "other":null
        },
        "parent":"j1_1"
    },
    {
        "id":"j1_8",
        "text":"Space",
        "icon":"../img/folder.png",
        "li_attr":{
            "id":"j1_8"
        },
        "a_attr":{
            "href":"#",
            "id":"j1_8_anchor"
        },
        "state":{
            "loaded":true,
            "opened":true,
            "selected":false,
            "disabled":false
        },
        "data":{
            "create_date":16839,
            "marked":false,
            "success":0,
            "failure":0,
            "audio_path":null,
            "note":null,
            "other":null
        },
        "parent":"j1_4"
    },
    {
        "id":"j1_35",
        "text":"Earth Science 1086G",
        "icon":"../img/red-x.png",
        "li_attr":{
            "id":"j1_35"
        },
        "a_attr":{
            "href":"#",
            "id":"j1_35_anchor"
        },
        "state":{
            "loaded":true,
            "opened":false,
            "selected":true,
            "disabled":false
        },
        "data":{
            "create_date":16839,
            "marked":true,
            "success":0,
            "failure":0,
            "audio_path":null,
            "note":null,
            "other":null
        },
        "parent":"j1_8"
    }
];
  return data;
}
